
#ifndef _DEFS_
#define _DEFS_

#include "cstdio"

typedef unsigned int UINT;

#define DEBUG 1

#if DEBUG == 1
#define dprint(...) printf(__VA_ARGS__)
#else
#define dprint(...)
#endif
typedef enum _ePieceType
{
	UNDEF,
	ROCK,
	PAPER,
	SCISSORS,
	BOMB,
	JOKER,
	FLAG,

	PIECE_COUNT

} ePieceType;

typedef enum _eScore
{
	WIN,
	LOSE,
	TIE,
	ERROR
} eScore;


#define DOUBLE_REASON_MASK 0x80
#define MAKE_REASON_DOUBLE(r) (r | DOUBLE_REASON_MASK)

typedef enum  _reason
{
	INVALID_REASON,

	FLAGS_CAPTURED,
	PIECES_EATEN,
	MOVES_INPUT_FILES_DONE,
	ALL_FLAGS_EATEN_DURING_POSITIONING,
	BAD_POSITIONING_INPUT_FILE_FORMAT,
	BAD_POSITIONING_INPUT_FILE_DOUBLE_POSITION,
	BAD_POSITIONING_INPUT_FILE_PIECE_NUMBER,
	BAD_POSITIONING_INPUT_FILE_FLAG_NUMBER,
	BAD_MOVES_INPUT_FILE,

	BOTH_BAD_POSITIONING_INPUT_FILE_FORMAT			= MAKE_REASON_DOUBLE(BAD_POSITIONING_INPUT_FILE_FORMAT),
	BOTH_BAD_POSITIONING_INPUT_FILE_DOUBLE_POSITION = MAKE_REASON_DOUBLE(BAD_POSITIONING_INPUT_FILE_DOUBLE_POSITION),
	BOTH_BAD_POSITIONING_INPUT_FILE_PIECE_NUMBER	= MAKE_REASON_DOUBLE(BAD_POSITIONING_INPUT_FILE_PIECE_NUMBER),
	BOTH_BAD_POSITIONING_INPUT_FILE_FLAG_NUMBER		= MAKE_REASON_DOUBLE(BAD_POSITIONING_INPUT_FILE_FLAG_NUMBER),
	
} eReason;


#endif //_DEFS_

